http_path = "/"
css_dir = "assets/css"
sass_dir = "scss"
images_dir = "assets/img"
javascripts_dir = "assets/js"
output_style = :expanded #:compressed 
sourcemap = true
relative_assets = true
line_comments = false
